// Definir os "nomes" de cada Action como uma string única
// Não pode haver ações diferentes com o mesmo nome

//ações das viagens
export const ADD_VIAGEM = "ADD_VIAGEM";

export const FETCH_VIAGEMS = "FETCH_VIAGEMS";
export const VIAGEMS_FETCH_SUCCEEDED = "VIAGEMS_FETCH_SUCCEEDED";
export const VIAGEMS_FETCH_ERROR = "VIAGEMS_FETCH_ERROR";

export const FETCH_VIAGEM = "FETCH_VIAGEM";
export const VIAGEM_FETCH_SUCCEEDED = "VIAGEM_FETCH_SUCCEEDED";
export const VIAGEM_FETCH_ERROR = "VIAGEM_FETCH_ERROR";

//ações dos produtos
export const ADD_PRODUTO = "ADD_PRODUTO";

export const FETCH_PRODUTOS = "FETCH_PRODUTOS";
export const PRODUTOS_FETCH_SUCCEEDED = "PRODUTOS_FETCH_SUCCEEDED";
export const PRODUTOS_FETCH_ERROR = "PRODUTOS_FETCH_ERROR";

export const FETCH_PRODUTO = "FETCH_PRODUTO";
export const PRODUTO_FETCH_SUCCEEDED = "PRODUTO_FETCH_SUCCEEDED";
export const PRODUTO_FETCH_ERROR = "PRODUTO_FETCH_ERROR";

//ações dos users
export const ADD_USER = "ADD_USER";

export const FETCH_USER = "FETCH_USER";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";

//ações das reviews
export const ADD_REVIEW = "ADD_REVIEW";

export const FETCH_LEADERBOARDPOINTS = "FETCH_LEADERBOARDPOINTS";
export const LEADERBOARDPOINTS_FETCH_SUCCEEDED = "LEADERBOARDPOINTS_FETCH_SUCCEEDED";
export const LEADERBOARDPOINTS_FETCH_ERROR = "LEADERBOARDPOINTS_FETCH_ERROR";

export const FETCH_LEADERBOARDREVIEWS = "FETCH_LEADERBOARDREVIEWS";
export const LEADERBOARDREVIEWS_FETCH_SUCCEEDED = "LEADERBOARDREVIEWS_FETCH_SUCCEEDED";
export const LEADERBOARDREVIEWS_FETCH_ERROR = "LEADERBOARDREVIEWS_FETCH_ERROR";